services:
  - type: web
    name: your-app-name # IMPORTANT: Replace with your actual project name on Render (e.g., jyooooo-hack-hvk3)
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    # CRITICAL: This startCommand must be exactly as shown to point Gunicorn to run.py
    startCommand: PYTHONPATH=$PYTHONPATH:/opt/render/project/src gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0 # Ensure this matches the Python version Render is actually using (from your logs)
      - key: CHROMA_DB_PATH
        value: /opt/render/project/src/chroma_db
      - key: FLASK_ENV
        value: production
      # Add your Azure OpenAI keys here. These are crucial for your app's functionality.
      - key: AZURE_OPENAI_API_KEY
        value: your_azure_openai_key_here # IMPORTANT: Replace with your actual key
      - key: AZURE_OPENAI_ENDPOINT
        value: your_azure_openai_endpoint_here # IMPORTANT: Replace with your actual endpoint
    healthCheckPath: /health
    autoDeploy: true
