services:
  - type: web
    name: influai-rag
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    # Added PYTHONPATH to ensure 'app' module is found
    startCommand: PYTHONPATH=$PYTHONPATH:/opt/render/project/src gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Ensure this matches your local Python version if different
      - key: CHROMA_DB_PATH
        value: /opt/render/project/src/chroma_db
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
